### ISSUE TITLE
Openpyxl

### ISSUE THREAD

**Issue by umamahesh0123** [didillysquat/SymPortal_framework#127]
Hello,

openpyxl can be used to update xlsm file ? 
When we use 'workbook.save"  ==> I can see the xlsm file is updated properly, but the macro buttons can't see any more.

**Before the xlsm file update:**
![image](https://user-images.githubusercontent.com/77699409/195278161-65a9b23a-eac5-4eb4-b8eb-16ab972536a6.png)

**After update xlsm file**  
The buttons can't see any more.

**Comment by didillysquat** [comment]
This is not the Openpyxl repository!
