### ISSUE TITLE
Sample-sheet links are down.

### ISSUE THREAD

**Issue by Caffenicotiak** [didillysquat/SymPortal_framework#130]
Hey,

The links to both, the blank(https://symportal.org/static/resources/SymPortal_datasheet_20190419.xlsx) and the example(http://symportal.org/static/resources/smith_et_al_ISMEJ_example_data.zip) sample sheets are down (giving Error 404).

It would be great having them accessible again.

Thanks for the great work,
Chris

**Comment by greenjune-ship-it** [comment]
Hey @Caffenicotiak 

It seems like there were old links to the documentation, I've updated the link to the [actual datasheet](https://symportal.org/static/resources/SymPortal_datasheet_20220722.xlsx). 

The link to the example dataset was restored and should work again. Please, check.

Best regards,
Yulia
