### ISSUE TITLE
Any suggestions to use symportal with low coverage whole genome data?

### ISSUE THREAD

**Issue by GenericUsername23094582** [didillysquat/SymPortal_framework#132]
Hi,

I extracted DNA from coral tissue and sent it for low coverage whole genome sequencing.  My data should contain reads from coral, symbionts, and other holobiont community members.

The fastq files I received from the sequencing center are smaller than the ITS region, and don't contain any primer sequences.  So in its current state, my data is incompatible with symportal, I believe. 

I could attempt to blast my data to ITS2 sequences, then assemble the hits into ITS2 regions and add primer sequences.  But this seems like a lot of work, and I fear that the assembly would likely be highly inaccurate due to the repetitive nature of the ITS region.  

Are you aware of anyone using symportal with this type of data, and do you have any suggestions?  Do you think it can be done reliably, or is this type of data fundamentally incompatible with symportal?

Thank you!

**Comment by greenjune-ship-it** [comment]
Dear @GenericUsername23094582 

SymPortal framework was designed to resolve the algal symbionts of reef corals using the ITS2 rDNA metabarcoding data.
The support of the WGS data analysis is not planned to be included.

Best regards,
Yulia

**Comment by GenericUsername23094582** [comment]
Hi, 

Understood, thank you for your reply.
