### ISSUE TITLE
Loading Single end read sequences

### ISSUE THREAD

**Issue by luuluDebbs** [didillysquat/SymPortal_framework#133]
Hello, I am trying to use the local version of symportal , but I am struggling with loading my Single End sequence reads. Is there a way I can load my data into symportal locally. I tried using only the forward reads (R1), but it did not work.

**Comment by reefgenomics** [comment]
hello, we are no longer supporting local installs, instead we focus on the web version at symportal.org; also, please note that SymPortal requires overlapping paired end ITS2 reads generated with the SymVar primers .. you can find all the details in the manuscript https://onlinelibrary.wiley.com/doi/full/10.1111/1755-0998.13004 .. kind regards

**Comment by luuluDebbs** [comment]
Thank you for the reply, I used ITS2intfor and ITSrev primers for my sequences. Can Symportal work for my sequences?

Best,

**Comment by luuluDebbs** [comment]
Okay I will.
