### ISSUE TITLE
Output master fasta alignment and tree from distance operations

### ISSUE THREAD

**Issue by didillysquat** [didillysquat/SymPortal_framework#34]
The UniFrac method is not working as well as I would have imagined it to. Currently we are defaulting to the BrayCurtis method so this is not time critical. But, it is difficult to assess where things are going awry without having access to the alignment that the tree was built from (well actually its one alignment per repetition) and the consensus tree itself.

I think it would be useful to developers and users to have this information.

**Comment by rmcminds** [comment]
What do you mean when you say the UniFrac method isn't working well? I have produced a couple phylogenies of the output profiles using UniFrac distances and the fastME (minimum evolution) model, which seem very reasonable to me. In fact I've struggled to produce profile phylogenies that pass the gut-check using any other method. I'm happy to provide code.

**Comment by didillysquat** [comment]
The aligned fastas and trees are now output by default as part of the new Unifrac calculation in v0.3.11.
