### ISSUE TITLE
manage the django.db.utils.OperationalError: too many SQL variables in virtual_objects setup

### ISSUE THREAD

**Issue by didillysquat** [didillysquat/SymPortal_framework#41]
The sqlite db is getting overwhelmed and complaining when we have large filer operations.

`DataSetSample.objects.filter(id__in=self.virtual_obj_manager.list_of_data_set_sample_uids)`

This looks like a good solution:
https://stackoverflow.com/a/18181477/5516420

Basically catch the error and cut the query up into chunks and stick back together into a list.

**Comment by didillysquat** [comment]
This is a pain to fix!

I can't use a decorator and I can't see how to abstract it to any kind of a method. I'm going to have to modify every instance of a .filter. I'm also going to have to make sure to call list() around the query as they are normally lazy and so won't cause an error at the point of calling but rather later on. I'm also going to have to make sure that the variable name I am setting the query to does not have a further .filter called on it as this will likely break once I have explicitly converted the query to a list.

Oh well...

**Comment by didillysquat** [comment]
Actually, we don't have to address every call to .filter, only those calls that use the form XXX__in=

**Comment by HughWarrington** [comment]
Why wait for the error to occur? Based on the Stackoverflow link above, you can determine exactly when you need to chunk (based on SQLITE_MAX_VARIABLE_NUMBER). This makes the code simpler, and by avoiding the failed queries, faster. Also OperationalError could mean more than one thing, not just that you need to chunk.

**Comment by didillysquat** [comment]
Yeah good point. I should just do a conditional against that variable I
guess and then chunk if needed.

I’m not sure how much simpler I can make the code though because checking
whether I need to chunk and then chunking takes up some lines.

Thanks for the feedback on this. I appreciate it.

I’m pretty exhausted by this constant updating... I’m guessing it never
really ends either so long as the development continues.

I need to toughen up to it :)

**Comment by HughWarrington** [comment]
You could unconditionally divide into chunks -- since your chunking code works however many ids are in the list (even if they all fit in a single chunk).

```python
def _chunked_query_dss_from_ds_uids(self):
    try:
        data_set_samples = list(DataSetSample.objects.filter(id__in=self.list_of_data_set_uids))
    except django.db.utils.OperationalError:
        print('Chunking query')
        data_set_samples = []
        for uid_list in general.chunks(self.list_of_data_set_uids, 100):
            data_set_samples.extend(list(DataSetSample.objects.filter(id__in=uid_list)))
    return data_set_samples
```

could become

```python
def _chunked_query_dss_from_ds_uids(self):
    data_set_samples = []
    for uid_list in general.chunks(self.list_of_data_set_uids, SQLITE_MAX_VARIABLE_NUMBER):
        data_set_samples.extend(DataSetSample.objects.filter(id__in=uid_list))
    return data_set_samples
```

**Comment by didillysquat** [comment]
Smart!

Thanks man.

I didn’t think to have the fix as the default.

Now I feel like the ‘help wanted’ tag on the issue is like a bat signal to
Waz!

Ha ha ha ha

**Comment by didillysquat** [comment]
Thanks @HughWarrington . Much better.
