### ISSUE TITLE
Improve/Fix UniFrac calculations

### ISSUE THREAD

**Issue by didillysquat** [didillysquat/SymPortal_framework#45]
The current implementation of UniFrac we have is giving poor results compared to a standard BrayCurtis distance implementation. The solution we currently have for calculating the UniFrac distances, whilst technically the most accurate, uses a lot of non-native python code, requires third party dependencies and at the end of the day, isn't doing that good a job.

Whilst BrayCurtis is actually doing a pretty good job at quantifying distances between ITS2 type profiles, a metric that takes into account sequence distance, should do an even better job. As such, I'd like to have another go at implementing UniFrac in SymPortal, this time using a suite of python methods from the scikit-bio package. This should remove the need for the third party packages. I also plan to implement the tree as a Nighbor-Joining tree, created from a distance matrix which is simply the pairwise-aligned hamming distances of the sequences.

Pseudo code would look something like this:
1 - Use the framework for the original UniFrac implementation to get the sequence abundances for the ITS2 type profiles or samples.
2 - Create the master .fasta and .name files as already implemented
3 - Use mothur (pairwise.seqs) to calculate distances between sequences (I can't find a decent python implementation for this.) We already depend on mothur for the rest of SymPortal so this still means no additional dependency.
4 - read in the distance matrix
5 - wrap this in the skbio DistanceMatrix
6 - make skbio.tree nj tree from the matrix
7 - use the beta_diversty implementation from skbio.diversity to calculate the unifrac
8 - Plug this distance matrix into the original functionality. (eventually include the dendrogram output. #33

**Comment by rmcminds** [comment]
I've had pretty good success creating a phylogeny of profiles using _unweighted_ UniFrac distances based on the profile definitions, followed by fastME (minimum evolution) phylogenetic inference. I haven't done any benchmarking (what dataset would you use to benchmark such a method with these data??), but suffice to say the trees I've gotten from this method have been much more realistic (subjectively) than with any other method I've used. I've now tried STAG, Astral, guenomu, and a couple others. Astral and guenomu don't output branch lengths, which is a no-go for some of my downstream analyses. STAG seems to have some potential, but it's actually just using its own distance matrix and then fastME internally, and the trees it produces are very 'laddered' and have unnaturally even branch lengths between nodes for some reason. It'd be interesting to incorporate the relative abundances of the DIVs using weighted UniFrac if I had access to the raw profile definitions. And this does seem like something that would be nice to include as a standard output. 

Can I help with this?

Are there non-phylogenetic interpretations you're going for with these profile distance matrices and hierarchical clusters?

**Comment by didillysquat** [comment]
Ryan,

Thanks again for taking the time to write!

Firstly, with regards to having access to the raw profile definitions, what exactly would you like? I agree that the advanced user will likely get a lot of milage out of having the abundances that define the ITS2 type profiles. I currently have a row in the ITS2 type profile output file that gives the mean abundance and standard deviation of each DIV for every ITS2 type profile.

For example for the ITS2 type profile: A4-A4b-A4c
As an entry for the row titled "Average defining sequence proportions and [stdev]": 0.569[0.042]-0.309[0.038]-0.122[0.034]

I appreciate that this is very lightweight documentation and I'd be happy to improve on this if you'd like to give me some direction in what you might be after.

I think its probably best that we open a separate issue for it. Please open an issue, link it to this one (no need to rewrite a description) and give it a title and we'll go from there.

**Comment by didillysquat** [comment]
With regards to the UniFrac: "It's not you, it's me". :). I was trying to be too thorough when doing the UniFrac distances and wanted to come up with a bootstrapped tree (or at least supported in some way) to work with. I was going to do this within some sort of likelihood framework, (i.e. raxml) but the generation time of such a tree was simply inhibitory. I want to avoid the generation of distance metrics become more time consuming than the actual analyses/loadings themselves. In short, I'm sure you can help, yes.

As with most things, the key is to find a balance between speed and effectiveness (biologically meaningful, as you touch on in your original comment). Another thing to bear in mind is that any tree we come up with would ideally contain all sequences currently encountered in SymPortal. Obviously this is a lot of sequences and is likely unrealistic within the speed we'd be looking for (feel free to disagree). Rather what might be a better option would be to represent all of the diversity (genotypic spread) of the sequences in the tree and then somehow post-hoc assign sequences to a closest matching branch? This way we could work with a much smaller tree. Given that the vast majority of sequences in Symbiodiniaceae are going to be <= 1bp different from one of the ancestral sequences .

It sounds like you've already made good progress on identifying what doesn't work.

Let's get you the abundance data that you want for the ITS2 type profiles. You obviously already have abundance data for sequences (we want distances for both the samples and the ITS2 type profiles). A good dataset to benchmark on would be yours (they don't get bigger than that).

If we can work together to implement an effective means of calculating these weighted UniFracs, then I can implement them. One further consideration, the programmes the end user has to install, the better :). That being said, I'm currently using the Phylip suite which is very difficult to install.

**Comment by rmcminds** [comment]
Hey Ben,

The abundance data was exactly what you already had included as "Average defining sequence proportions and [stdev]". I knew those were there and somehow didn't put 2 + 2 together when separately discussing the split of metadata like that from the count matrices.

I've included those abundances in a new ipython pipeline that produces a reasonable tree. For the moment, working in ipython, I've uses a couple packages that aren't currently in your dependencies and might be overkill for the automated methods you want (ete3, iqtree, fastme, ape). However, I should be able to make something like the pipeline you've suggested and then do a comparison of the two methods?

Regarding UniFrac specifically, I'm finding the skbio implementation a little bit clunky. It appears to require integer data (it doesn't throw an error when the proportions are supplied - just produces nonsense results). With the proportions you've provided, it's easy enough to multiply by 1000 and cast as an integer, but it's certainly an ugly hack. I was also considering applying some kind of transformation to the proportions to account for compositionality, but the skbio implementation automatically normalizes the input to proportions internally, which would mess with any such transformation. The calculations aren't too complex, so it might be worth just coding it manually??

As far as sequence inclusion goes, I agree the entire dataset is too much for many purposes. My experimental pipeline is only including seqs used as DIVs and I don't see how inclusion of most non-DIV seqs would help much for the primary goal of understanding the relationships among profiles. That being said, a FastTree/UniFrac/FastME pipeline could probably handle all sequences, and a neighbor-joining method (for both divs and profiles) should do even better in terms of speed and memory. We will have to see whether my pipeline using iqtree and FastME produces substantially different results...

**Comment by didillysquat** [comment]
Hey Ryan,

Nice work. Sorry that I've been MIA.

> The abundance data was exactly what you already had included as "Average defining sequence proportions and [stdev]". I knew those were there and somehow didn't put 2 + 2 together when separately discussing the split of metadata like that from the count matrices.

_Wonderful_

> With the proportions you've provided, it's easy enough to multiply by 1000 and cast as an integer, but it's certainly an ugly hack.

_Mate, I do this all the time. It turns out that lots of processes take integer abundances rather than float proportions. In the greater scheme of things, ugly is fine, and the time it takes to do these multiplications will not be noticeable. As such, I deem this totally acceptable._

> Regarding UniFrac specifically, I'm finding the skbio implementation a little bit clunky.

_I honestly just had to go into the code to see what I used for the implementation. I use the mothur implementation currently. I think I did know that skbio had an implementation but only found that out after I'd got it up and running in Mothur. If possible it would be good to plug your tree into the current implementation I have of UniFrac (via mothur). Only to minimise work. However, if you've already created a pipeline that goes from your tree straight into the skbio implementation, then let's transfer over to that. Alternatively, as I already have the process of creating the UniFrac distances fairly modular, we could start with your tree, and then have a choice of implementation via UniFrac or skbio._

> The calculations aren't too complex, so it might be worth just coding it manually??

_:) If you want to step up to that one, then you're more than welcome, but I'd tend to stick to the skbio or mothur implementation if possible. (again, just to save time). I've got way cooler stuff for us to be working on if you find yourself in need of some python coding :)_

> I was also considering applying some kind of transformation to the proportions to account for compositionality, but the skbio implementation automatically normalizes the input to proportions internally, which would mess with any such transformation.

_Hmmm... would it? Maybe I'm being an idiot here, but if we multiply by the proportions by some big number and then square root these abundances then the internal proportions made in the skbio will still reflect the transformation, right? Well, that's what I do when calculating bray curtis, so I hope that's true :)._

> My experimental pipeline is only including seqs used as DIVs and I don't see how inclusion of most non-DIV seqs would help much for the primary goal of understanding the relationships among profiles.

_Agreed, if your proposed pipeline is handling all of the DIVs (i.e. those sequences used in the definition of ITS2 type profiles), then thats great. As you say, the other sequences will add nothing to the accuracy of the tree._

**Moving forward**

OK so in terms of moving this forward, it sounds like I should have a look through your ipython and see if I can understand it and convert it into something that I can integrate directly into the SymPortal code. I didn't quite follow what your comparisons would be between. Let's make the assumption that my approach to making the tree (i.e. with PHYLIP modules) is broken and should be thrown in the bin.

The other option of course is for you to take the leap and see if you'd like to have a go at implementing it into the code yourself (with my support). You could create a separate branch from either the master or local_dev branches and we could go from there. I could help you with the database querying syntax and setting you up your local instance of SP with a populated database to work with on your local machine. Up to you, it would likely represent quite a large investment of time on your end but it would be good to have another coder on board!!! (Feel free to say no :) )

**Comment by didillysquat** [comment]
I've just seen that it was my own suggestion to move towards the skibio implementations back in April. God its embarrassing how I forget this stuff. I guess that's why we write it down.

**Comment by rmcminds** [comment]
I think you'll probably want me to clean up my pipeline notebook a bit before you try to translate it. 

Importantly, what is your feeling on the addition of the external tools iqtree and fastme? If you're really just trying to produce something quick and dirty, and don't want the extra dependencies, then I probably haven't done much to help you. My idea for comparisons would be a somewhat subjective look at whether iqtree is better than, say, FastTree or whatever neighbor-joining method you were going to use, and whether fastME is better than neighbor-joining. 

If you want to take a look at the notebook, feel free, but don't hate me for being a python n00b and mixing in a few shell commands and exploring a few other tree methods...

[GCMP SymPortal pipeline](https://github.com/rmcminds/gcmp_stan_symportal/blob/master/phylogenetics/separate_symbio_clades.ipynb)

About the normalization in UniFrac (or potentially Bray-Curtis) - you are correct if the entire matrix is scaled by the same number, or I believe even if each taxon is scaled separately. But If the transformation affects each sample (or in this case profile) differently, then it'd be funky. But I think the only such transformations I had in mind are very specific to count data, so it shouldn't matter here, where the profile definitions are inherently proportions.

And yes, I was going off your own desire to move to skibio...

**Comment by rmcminds** [comment]
ok it was actually easier to clean that up than i expected. go ahead and take a look. 

I'm happy to take a swing at implementing it myself, but for your own sake it might be easier to just try to integrate things into your own code. I'll fumble around with making a branch and identifying the relevant code...

**Comment by didillysquat** [comment]
I've played around with Ryan's workflow and I have a prototype unifrac process working. Thanks @rmcminds . It is slow, due to the creation of a tree per clade and doing alignments per clade. This is not ideal. Its also largely unavoidable to some extent. To improve the speed I think we can do two things:

1. Have a large precomputed tree available as part of the standard repo that users will be able to use. This has its own limitations of course because we will have to ensure that sequence identities can be maintained across different instances of SymPortal (i.e. the remote version and a user's version). I think the best way to ensure sequence identity is to work with hash code identities for the sequences. Thanks @HughWarrington. So instead of naming the sequences either according to the UID (these will not be maintained between instances of SymPortal) or names (these will only be maintained for named sequences, i.e. those that have been used as DIVs), we will hash the actual nucleotide sequences and use this hash as the name. We will then keep a hash to name or UID dictionary in the code so that we can relate the two.

2. Give the user the option to place novel sequences onto the precomputed trees. I don't know how fast this will be and we will have to play around with pplacer (Ryan's recommendation, and a good one) but it should in theory save a lot of time in computing novel trees when many sequences are involved. 

Both of these options will take a bit of development time and I will raise them as separate issues to be worked on. For the time being I will finish off a 'vanilla' version of the unifrac, in which the new trees are generated from scratch each time. Once, this is complete I'll close off this issue.

**Comment by didillysquat** [comment]
Vanilla implementation of UniFrac is now restored and seems to work great. I'm closing this now. Thanks @rmcminds. Your ipython was instrumental.

**Comment by rmcminds** [comment]
sweet! glad to hear it was useful. I had my doubts ;)
