### ISSUE TITLE
Separate output abundance matrices from other output summary data

### ISSUE THREAD

**Issue by rmcminds** [didillysquat/SymPortal_framework#62]
Currently, the output abundance data for both DIVs and profiles is contained in a tab-delimited file with multiple rows and columns that do not correspond to abundance data. This makes it necessary to add an extra filtering step when importing the data for downstream analysis. It's not entirely clear whether the number of these columns is consistent from run-to-run, so this filtering step requires some manual inspection and counting of the rows and columns. It could be more convenient to instead have 'clean' matrices plus separate summary statistics tables.

Obviously it's not too big a deal to parse the tables as they currently are, so if there's any strong argument for not changing things (such as strong feelings about keeping all the relevant info in the same place), that's fine by me.

Columns in the 'seqs' files that would be stripped:
- sample_name	
- raw_contigs	
- post_qc_absolute_seqs	
- post_qc_unique_seqs	
- post_taxa_id_absolute_symbiodinium_seqs	
- post_taxa_id_unique_symbiodinium_seqs	
- size_screening_violation_absolute	
- size_screening_violation_unique	
- post_taxa_id_absolute_non_symbiodinium_seqs	
- post_taxa_id_unique_non_symbiodinium_seqs	
- post_med_absolute	
- post_med_unique

Rows at the end of the 'seqs' files:
- seq_accession
- meta_info_summary
- data_set_info
- data_set_info
- data_set_info

Rows at the beginning of the 'profiles' files:
- Clade
- Majority ITS2 sequence
- Associated species
- ITS2 type abundance local
- ITS2 type abundance DB
- ITS2 type profile

Rows at the end of the 'profiles' file:
- Sequence accession / SymPortal UID
- Average defining sequence proportions and [stdev]
- Species reference
- S. goreaui
- S. pseudominutum
- S. tridacnidorum
- S. endomadracis
- S. linucheae
- S. glynnii
- S. psygmophilum
- S. trenchii
- S. microadriaticum
- S. antillogorgium
- S. natans
- S. minutum
- meta_info_summary
- data_set_info
- data_set_info
- data_set_info

Also potentially the untitled column in the 'profiles' files that has sample names.

I could also see some other compromise, such as leaving the rows in the table but leading them with a standard pattern such as '#'. Or the opposite: making it easy to select all the abundance columns by leading their headers with a standard pattern. Or... if we have confidence that the number of metadata columns will always stay the same, maybe it's all moot.

**Comment by didillysquat** [comment]
Hey Ryan,

Thanks for taking the time to put up such a detailed issue!

Firstly, the number of columns that are non-data, will be standard within analyses/loadings run from the same version of SymPortal. However, standardisation cannot be ensured between versions. Infact, I would go as far as to say that it will likely differ. For rows, they will differ depending on the sequences or ITS2 type profiles returned in the data (as this effects which formal species descriptions need to be associated). 

Obviously I work with these tables a lot and I know your pain at removing these superfluous meta cols/rows. We need to find a balance for the user who wants to drag this all into excel and have everything laid out in front of them, and the user who wants to load this into a DataFrame programmaticaly. I think for the former user, current format is good. For the latter, your 'clean' format makes excellent sense. As such, I would suggest that we keep an output in the current format and add an additional paired 'clean' version (paried being, UID and abundance only version twinned with a meta table).

If you think that sounds good, I'll make it happen.

Thanks again for taking the time to write!

**Comment by didillysquat** [comment]
implement with #66

**Comment by didillysquat** [comment]
Probably a good idea to add in the other user defined meta info here to the output tables, i.e. host taxa info, long lat etc.

**Comment by didillysquat** [comment]
I think we should put the species reference information, the meta_info and data set info for the data_analysis output into a separate 'additional_info.txt' file. Then, when we output the the abund and meta, the abund will be by sample, but the meta will be by type.

**Comment by didillysquat** [comment]
Do as above but for the seq info as well, i.e. have an additional_info.txt file
